// Semua copy landing page — satu versi netral, tanpa segmentasi audience.
// Konsep: self-serve — user ketik keinginan → AI generate gambar dekorasi.
// Opsi lanjut: "dikerjain tim" untuk aset final rapi (hybrid monetisasi).

export const content = {
  brand: 'Decora AI',
  nav: [
    { label: 'Coba', href: '#generator' },
    { label: 'Cara Kerja', href: '#cara-kerja' },
    { label: 'Contoh Hasil', href: '#portofolio' },
    { label: 'Harga', href: '#harga' },
    { label: 'FAQ', href: '#faq' },
  ],

  hero: {
    headline: 'Ketik dekorasi impianmu, lihat langsung jadi gambar.',
    sub: 'Sebutkan gaya, adat, warna, dan budgetmu — AI langsung menyusun visualnya, siap kamu tunjukkan ke pasangan, keluarga, atau vendor.',
    ctaPrimary: 'Buat Desain Pernikahan',
  },

  problems: {
    lead: 'Jangan cuma membayangkan — lihat dulu hasilnya, sebelum satu rupiah pun keluar.',
    body: 'Dari ide yang masih samar sampai visual yang bisa kamu tunjukkan — ke pasangan, ke keluarga, ke vendor. Desain dulu, baru putuskan.',
  },

  howItWorks: {
    titleLead: 'Dari ketikan, jadi ',
    titleAccent: 'gambar nyata.',
    sub: 'Dari gagasan awal sampai aset siap dibawa ke vendor — lima langkah, masing-masing dengan detail dan contohnya sendiri.',
  },

  packages: {
    title: 'Coba gratis, upgrade sesuai kebutuhan.',
    sub: 'Mulai gratis dan generate sendiri. Untuk volume rutin atau hasil final yang rapi, tersedia paket lanjutan.',
    plans: [
      {
        name: 'Gratis',
        price: 'Rp0',
        tagline: 'Langkah pertama menuju desainmu',
        featured: false,
        features: [
          'Beberapa generate per hari',
          'Gaya dan budaya dasar',
          'Resolusi standar (ada watermark)',
          'Simpan hasil favorit',
        ],
        cta: 'Coba Gratis',
      },
      {
        name: 'Plus',
        price: 'Langganan bulanan',
        tagline: 'Generate lebih leluasa, hasil lebih maksimal',
        featured: true,
        features: [
          'Generate tanpa batas wajar',
          'Resolusi HD tanpa watermark',
          'Semua gaya dan kombinasi budaya',
          'Riwayat dan simpan banyak konsep',
        ],
        cta: 'Mulai Plus',
      },
      {
        name: 'Aset Final (Tim)',
        price: 'Per project',
        tagline: 'Dikerjakan tim, siap presentasi dan produksi',
        featured: false,
        features: [
          'Finalisasi jadi vector rapi berlayer',
          'Dikurasi pakem budaya oleh manusia',
          'Mockup presentasi siap pakai',
          'Termasuk revisi terbatas',
        ],
        cta: 'Pesan Aset Final',
      },
    ],
  },

  testimonials: {
    title: 'Kata mereka yang sudah mencoba.',
    // Dua kolom audiens (PRODUCT.md: calon pengantin & pro dekorasi). Semua item
    // kartu testimoni: quote + highlight frasa kunci + name + role.
    columns: [
      {
        label: 'Calon Pengantin',
        items: [
          {
            quote: 'Aku ketik bayangan dekorasiku, langsung muncul gambarnya. Nunjukin ke vendor jadi gampang banget — gak perlu ribet jelasin.',
            highlight: 'gak perlu ribet jelasin',
            name: 'Dinda & Bagas',
            role: 'Menikah 2026, Jawa × modern',
          },
          {
            quote: 'Suamiku maunya Jawa, aku maunya minimalis. Di sini kita racik dua-duanya jadi satu gambar — langsung sreg, langsung deal.',
            highlight: 'jadi satu gambar',
            name: 'Ayu & Reza',
            role: 'Menikah 2025, Jawa × minimalis',
          },
          {
            quote: 'Sebelum keluar DP ke vendor, aku udah lihat bayangannya dulu. Jadi gak takut hasilnya meleset dari yang aku mau.',
            highlight: 'gak takut hasilnya meleset',
            name: 'Nadia',
            role: 'Calon pengantin, Bandung',
          },
        ],
      },
      {
        label: 'Vendor & Decorator',
        items: [
          {
            quote: 'Tinggal ketik gaya yang klien mau, beberapa detik udah ada opsi visual buat presentasi. Yang final tinggal gue serahkan ke tim.',
            highlight: 'beberapa detik udah ada opsi visual',
            name: 'Rangga P.',
            role: 'Owner studio dekorasi, Yogyakarta',
          },
          {
            quote: 'Enaknya paham istilah adat. Ketik "paes ageng" langsung nyambung — gak keluar hasil ngawur kayak tools generic.',
            highlight: 'langsung nyambung',
            name: 'Sekar A.',
            role: 'Freelance wedding decorator',
          },
          {
            quote: 'Buat pitch klien baru, aku gak perlu begadang bikin mockup lagi. Beberapa opsi visual udah cukup buat klien milih arah.',
            highlight: 'gak perlu begadang bikin mockup',
            name: 'Bimo',
            role: 'Wedding organizer, Surabaya',
          },
        ],
      },
    ],
  },

  faq: {
    title: 'Pertanyaan yang sering muncul.',
    items: [
      {
        q: 'Resolusi hasilnya seperti apa?',
        a: 'Paket Gratis menghasilkan resolusi standar dengan watermark — cukup untuk dibayangkan dan didiskusikan. Paket Plus memberi resolusi HD tanpa watermark, siap dipakai untuk presentasi resmi atau dibagikan ke vendor.',
      },
      {
        q: 'Apakah ini menggantikan jasa decorator?',
        a: 'Bukan. Decora AI membantumu memantapkan konsep dan mempermudah presentasi atau negosiasi. Eksekusi fisik tetap dilakukan vendor atau decorator pilihanmu. Untuk hasil siap produksi, tersedia opsi tim.',
      },
      {
        q: 'Seberapa akurat dengan pakem budaya?',
        a: 'AI kami dilatih khusus mengenali istilah dan gaya dekorasi Nusantara — gebyok, paes ageng, janur, dan sejenisnya. Untuk hasil yang benar-benar sesuai pakem dan siap produksi, tim kami yang berpengalaman dalam adat menjadi lapisan kurasi terakhir.',
      },
      {
        q: 'Bisa dipakai komersial?',
        a: 'Bisa. Hasil generate maupun aset final boleh dipakai untuk presentasi, proposal, maupun negosiasi ke klien atau vendor.',
      },
      {
        q: 'Kalau hasilnya belum sesuai, bagaimana?',
        a: 'Ubah deskripsimu dan generate ulang — sebanyak yang kamu butuhkan di paket berbayar. Kalau masih belum pas, tim kami siap menyempurnakannya secara langsung.',
      },
    ],
  },

  generator: {
    placeholder: 'Contoh: pelaminan Jawa modern, dominan putih dan emas, dengan gebyok ukir dan janur, nuansa hangat, budget menengah',
  },

  reference: {
    label: 'Referensi gambar (opsional)',
    hint: 'Unggah foto lokasi, Pinterest, atau referensi gaya yang kamu suka',
    add: 'Tambah gambar referensi',
    change: 'Ganti gambar',
    remove: 'Hapus',
  },

  // Copy untuk area aplikasi (setelah login). Satu bahasa dengan landing —
  // uiuxcontext.md: satu pengalaman produk yang konsisten, bahasa Indonesia.
  app: {
    auth: {
      title: 'Masuk ke Decora AI',
      registerTitle: 'Buat akun Decora AI',
      sub: 'Lanjutkan mendesain dekorasi pernikahanmu.',
      registerSub: 'Gratis — langsung mulai desain pertamamu.',
      emailLabel: 'Email',
      passwordLabel: 'Kata sandi',
      nameLabel: 'Nama',
      submit: 'Masuk',
      registerSubmit: 'Daftar',
      submitting: 'Sebentar…',
      google: 'Lanjutkan dengan Google',
      or: 'atau',
      toRegister: 'Belum punya akun? Daftar',
      toLogin: 'Sudah punya akun? Masuk',
      note: 'Versi demo — kredensial apa pun diterima.',
    },
    shell: {
      projects: 'Proyek',
      settings: 'Pengaturan',
      logout: 'Keluar',
      saving: 'Menyimpan…',
      saved: 'Tersimpan',
      notSynced: 'Belum tersinkron',
      notSyncedHint: 'Perubahan tersimpan di perangkat ini; sinkronisasi server dicoba ulang',
    },
    library: {
      title: 'Proyek',
      welcome: (name) => `Halo, ${name} 👋`,
      newProject: 'Proyek baru',
      statProjects: 'Proyek aktif',
      statDesigns: 'Total desain',
      statFavorites: 'Favorit',
      statToday: 'Desain hari ini',
      planFree: 'Gratis',
      planPlus: 'Plus',
      planUpgrade: 'Upgrade',
      continueTitle: 'Lanjutkan mengerjakan',
      continueCta: 'Buka Studio →',
      continueUpdated: 'Terakhir diperbarui',
      emptyTitle: 'Mulai desain pertamamu',
      emptyBody: 'Jawab beberapa pertanyaan tentang pernikahanmu — AI langsung membuatkan konsepnya.',
      designCount: 'desain',
      updated: 'Diperbarui',
      rename: 'Ubah nama',
      duplicate: 'Duplikat',
      delete: 'Hapus',
      deleteTitle: (name) => `Hapus '${name}'?`,
      deleteBody: (n) => `Proyek beserta ${n} desainnya akan dihapus. Tindakan ini tidak bisa dibatalkan.`,
      deleted: (name) => `"${name}" dihapus`,
      undo: 'Urungkan',
      cancel: 'Batal',
      degraded: 'Menampilkan desain yang tersimpan di perangkat ini. Sinkronisasi server tidak tersedia.',
    },
    wizard: {
      title: 'Ceritakan pernikahanmu',
      editTitle: 'Ubah setup',
      sub: 'Hanya tema dan venue yang wajib — sisanya bikin desainnya makin pas.',
      teaserNotice: 'Proyekmu sudah dimulai dari idemu — tambahkan beberapa detail biar hasilnya makin bagus.',
      nameLabel: 'Nama proyek',
      defaultName: 'Pernikahan tanpa judul',
      sectionWedding: 'Pernikahannya',
      sectionVenue: 'Venuenya',
      sectionLook: 'Tampilannya',
      themeLabel: 'Tema',
      themeError: 'Pilih tema dulu untuk lanjut',
      styleLabel: 'Gaya (opsional)',
      venueLabel: 'Tipe venue',
      venueError: 'Pilih tipe venue dulu untuk lanjut',
      venueSizeLabel: 'Ukuran venue',
      guestLabel: 'Jumlah tamu',
      guestUnit: 'tamu',
      guestClamped: (min, max) => `Dijaga antara ${min} dan ${max}.`,
      budgetLabel: 'Kelas budget',
      budgetHelper: 'Menentukan semewah apa tampilan desainnya.',
      paletteLabel: 'Palet warna (opsional)',
      paletteLimit: 'Maksimal 3 warna biar desainnya tetap serasi.',
      paletteCustom: 'Kustom',
      paletteAdd: 'Tambah',
      notesLabel: 'Catatan tambahan (opsional)',
      notesPlaceholder: 'Hal spesifik — mis. banyak lampu tumblr, floral arch, tanpa warna merah.',
      customPlaceholder: 'Tuliskan sendiri',
      cancel: 'Batal',
      preview: 'Pratinjau prompt →',
      backToForm: '← Ubah detail',
      promptEyebrow: 'Prompt generate-mu',
      promptNote: 'Silakan ubah kata-katanya. Jawabanmu di atas sudah terangkum di sini.',
      recompileBanner: 'Kamu mengubah prompt ini manual.',
      recompileAction: 'Susun ulang dari jawabanmu',
      recompileKeep: 'atau pertahankan versimu.',
      generate: 'Buat desain ✦',
      saveChanges: 'Simpan perubahan',
      creating: 'Menyimpan…',
      notFound: 'Proyek ini tidak ada atau sudah dihapus.',
      backToProjects: 'Kembali ke proyek',
    },
    studio: {
      emptyTitle: 'Belum ada desain',
      emptyBody: 'Tulis catatan di bawah (atau langsung tekan Buat Desain) untuk melihat konsep pertamamu.',
      design: 'Desain',
      generating: 'Membuat…',
      generatingElapsed: 'Membuat desain…',
      patience: 'Desain yang kompleks bisa butuh sampai beberapa menit.',
      generate: 'Buat Desain',
      composerPlaceholder: 'Tulis apa yang mau diubah — atau kosongkan untuk membuat ulang',
      analyze: 'Analisis',
      viewChecklist: 'Lihat checklist',
      export: 'Ekspor',
      useAsReference: 'Jadikan referensi',
      isReference: 'Referensi ✓',
      refChip: 'Ref: Desain',
      removeRef: 'Hapus referensi',
      retry: 'Coba lagi',
      prompt: 'Prompt',
      tabSetup: 'Setup',
      tabHistory: 'Riwayat',
      tabAnalyze: 'Analisis',
      analyzingBadge: 'Sedang dianalisis →',
      editSetup: 'Ubah setup',
      historyEmpty: 'Belum ada desain.',
      setupTheme: 'Tema',
      setupStyle: 'Gaya',
      setupVenue: 'Venue',
      setupSize: 'Ukuran',
      setupGuests: 'Tamu',
      setupBudget: 'Budget',
      setupPalette: 'Palet',
      setupUpdated: 'Setup baru berlaku untuk desain berikutnya',
      designReady: 'Desain berhasil dibuat ✓',
      designFailed: 'Desain gagal dibuat',
      projectSaved: 'Proyek tersimpan ✓',
      notFound: 'Proyek ini tidak ada atau sudah dihapus.',
      backToProjects: 'Kembali ke proyek',
      errCap: (n) => `Batas desain harian proyek ini tercapai (${n}). Coba lagi besok.`,
      errConnectivity: 'Layanan desain tidak bisa dihubungi. Promptmu aman — coba lagi.',
      lightboxDownload: 'Unduh PNG',
      lightboxAnalyze: 'Analisis',
      lightboxClose: 'Tutup',
      sidebarProjects: 'Proyek',
      sidebarFeed: 'Feed',
      confirmGenerateTitle: 'Buat desain ini?',
      confirmGenerateBody: 'Proses ini memakai kredit AI generate gambar dan bisa butuh waktu beberapa menit. Pastikan promptmu sudah sesuai.',
      confirmGenerateCta: 'Ya, buat desain',
      cancel: 'Batal',
      cancelGenerating: 'Batalkan',
      cancelled: 'Dibatalkan',
    },
    analyze: {
      title: 'Checklist dekorasi',
      design: 'Desain',
      // Peta label tampilan ID — nilai data/enum tetap EN (tersimpan di project & schema server).
      categoryLabels: {
        Stage: 'Panggung',
        Backdrop: 'Backdrop',
        Chairs: 'Kursi Tamu',
        'VIP Chairs': 'Kursi VIP',
        Tables: 'Meja',
        Flowers: 'Bunga',
        Lighting: 'Pencahayaan',
        Walkway: 'Jalur Masuk',
        'Reception Desk': 'Meja Penerima Tamu',
        'Ceiling Decoration': 'Dekorasi Plafon',
        'LED Screen': 'Layar LED',
        Other: 'Lainnya',
      },
      costLabel: 'Estimasi biaya (Rp)',
      costChipPrefix: 'Rp',
      costTotal: 'Estimasi total',
      findVendors: 'Butuh vendor untuk mewujudkannya? Lihat vendor →',
      noDesignTitle: 'Belum ada desain',
      noDesignBody: 'Buat desain dulu di feed sebelah kiri, baru bisa dianalisis di sini.',
      jumpToFeed: 'Lihat di feed',
      cta: 'Analisis desain ini ✦',
      ctaHint: 'Butuh sekitar 15 detik.',
      analyzing: 'Menganalisis… ±15 detik',
      complete: 'Analisis selesai ✓',
      error: 'Desain ini belum bisa dianalisis. Coba lagi, ya.',
      retry: 'Coba lagi',
      zeroTitle: 'Belum ada item terdeteksi',
      zeroBody: 'Item dekorasi di desain ini belum bisa dikenali. Kamu bisa menambahkannya manual.',
      addItem: '＋ Tambah item',
      reanalyze: 'Analisis ulang',
      reanalyzeConfirm: 'Checklist beserta editanmu akan diganti. Analisis ulang?',
      cancel: 'Batal',
      exportBrief: 'Ekspor brief →',
      note: 'Catatan',
      generateItemImage: 'Buat gambar item',
      generatingItemImage: 'Membuat gambar item…',
      itemImageReady: 'Gambar item selesai ✓',
      itemImageError: 'Gambar item ini belum bisa dibuat. Coba lagi, ya.',
      regenerateItem: 'Buat ulang / kustomisasi',
      itemPromptPlaceholder: 'Opsional: jelaskan perubahan, mis. emas bukan perak',
      itemGenerate: 'Buat',
      itemGenerating: 'Membuat…',
      itemCancelling: 'Batalkan',
      itemCancelled: 'Dibatalkan',
      confirmItemTitle: 'Buat gambar item ini?',
      confirmItemBody: 'Proses ini memakai kredit AI generate gambar.',
      confirmItemCta: 'Ya, buat gambar',
    },
    compare: {
      action: 'Bandingkan',
      selected: 'Dipilih ✓',
      bar: (n) => `${n}/2 desain dipilih untuk dibandingkan`,
      open: 'Bandingkan sekarang',
      clear: 'Batal',
      title: 'Bandingkan desain',
      close: 'Tutup',
    },
    favorite: {
      add: 'Tandai favorit',
      remove: 'Hapus dari favorit',
    },
    share: {
      option: 'Link berbagi',
      optionDesc: 'Salin link lihat-saja untuk dikirim ke pasangan atau vendor.',
      copy: 'Salin link',
      copied: 'Link berbagi disalin ✓',
      copyFailed: 'Gagal menyalin — salin manual dari address bar.',
      pageTitle: 'Dibagikan dari Decora AI',
      pageNote: 'Halaman lihat-saja. Buat desainmu sendiri di Decora AI.',
      pageCta: 'Coba Decora AI',
      notFound: 'Link berbagi ini tidak valid atau desainnya sudah dihapus.',
    },
    vendors: {
      title: 'Vendor Dekorasi',
      sub: 'Vendor pilihan yang siap mewujudkan konsep desainmu. (Demo — data contoh)',
      contact: 'Hubungi vendor',
      contacted: 'Permintaan terkirim ke vendor ✓ (demo)',
      specialty: 'Spesialisasi',
      backToStudio: '← Kembali',
      list: [
        { name: 'Arunika Decor', city: 'Jakarta', specialty: 'Rustic & Garden', rating: 4.9, projects: 120 },
        { name: 'Gebyok Nusantara', city: 'Yogyakarta', specialty: 'Adat Jawa Klasik', rating: 4.8, projects: 200 },
        { name: 'Serenity Wedding', city: 'Bandung', specialty: 'Modern Minimalis', rating: 4.7, projects: 85 },
        { name: 'Puspa Kencana', city: 'Surabaya', specialty: 'Glamorous Ballroom', rating: 4.8, projects: 150 },
        { name: 'Bale Agung Decor', city: 'Bali', specialty: 'Outdoor & Beach', rating: 4.9, projects: 95 },
        { name: 'Selaras Pelaminan', city: 'Semarang', specialty: 'Sunda & Nasional', rating: 4.6, projects: 110 },
      ],
    },
    billing: {
      title: 'Paket & Tagihan',
      current: 'Paket saat ini',
      free: 'Gratis',
      plus: 'Plus',
      freeDesc: 'Beberapa generate per hari, resolusi standar.',
      plusDesc: 'Generate tanpa batas wajar, resolusi HD tanpa watermark.',
      upgrade: 'Upgrade ke Plus',
      downgrade: 'Kembali ke Gratis',
      upgraded: 'Berhasil upgrade ke Plus ✓ (demo)',
      downgraded: 'Kembali ke paket Gratis (demo)',
      demoNote: 'Demo — belum ada pembayaran sungguhan.',
    },
    export: {
      title: (n) => `Ekspor Desain ${n}`,
      png: 'Gambar (PNG)',
      pngDesc: 'Gambar desain dalam resolusi penuh.',
      pdf: 'Brief vendor (PDF)',
      pdfDesc: 'Satu halaman: desain, detail pernikahan, dan checklist.',
      noChecklist: 'Belum ada checklist — brief hanya berisi desain + detail.',
      analyzeFirst: 'Analisis dulu',
      cancel: 'Batal',
      download: 'Unduh',
      preparing: 'Menyiapkan…',
      pngDone: 'Gambar terunduh ✓',
      pdfDone: 'Brief terunduh ✓',
      error: 'Gambar desain tidak bisa diambil. Cek koneksimu lalu coba lagi.',
    },
    settings: {
      title: 'Pengaturan',
      profile: 'Profil',
      nameLabel: 'Nama',
      emailLabel: 'Email',
      save: 'Simpan profil',
      saved: 'Tersimpan ✓',
      appInfo: 'Info aplikasi',
      dailyCap: 'Batas generate harian per proyek',
      language: 'Bahasa',
      languageValue: 'Indonesia',
      logout: 'Keluar',
    },
    notFound: {
      title: 'Halaman tidak ditemukan',
      cta: 'Kembali ke proyek',
    },
  },

  stepsList: [
    {
      icon: 'brief',
      title: 'Tulis keinginan',
      body: 'Tuliskan gaya, adat, warna, elemen wajib, dan budget kamu. Atau pilih langsung dari contoh gaya yang tersedia.',
      breakdown: ['Pilih gaya dan adat dari contoh', 'Unggah foto referensi (opsional)', 'Tentukan budget, jumlah tamu, dan palet warna'],
    },
    {
      icon: 'spark',
      title: 'AI merancang visualnya',
      body: 'Dalam hitungan detik, beberapa opsi visual siap — memahami istilah dan gaya adat, bukan sekadar templat generik.',
      breakdown: ['Beberapa opsi dalam satu proses', 'Mengenali istilah gebyok, paes ageng, janur', 'Gaya lokal yang autentik'],
    },
    {
      icon: 'revise',
      title: 'Utak-atik sampai pas',
      body: 'Belum sesuai? Ubah sedikit, generate ulang — sebanyak yang kamu perlukan sampai hasilnya tepat.',
      breakdown: ['Ubah prompt dan generate ulang', 'Bandingkan beberapa versi', 'Simpan yang paling sesuai'],
    },
    {
      icon: 'checklist',
      title: 'Bedah tiap elemen',
      body: 'AI menguraikan gambar menjadi daftar elemen dekorasi — pelaminan, kursi, meja, backdrop, pencahayaan — lengkap dengan perkiraan biaya, siap dikirim ke vendor.',
      breakdown: ['Elemen terdeteksi otomatis', 'Estimasi biaya per item', 'Brief siap dikirim ke vendor'],
    },
    {
      icon: 'produce',
      title: 'Upgrade ke tim',
      body: 'Opsional: desain pilihanmu disempurnakan oleh tim menjadi aset final — vector berlayer, dikurasi sesuai pakem adat.',
      breakdown: ['Vector rapi dan berlayer', 'Dikurasi sesuai pakem adat', 'Mockup presentasi siap pakai'],
      optional: true,
    },
  ],

  gallery: {
    title: 'Ragam padu padan budaya.',
    sub: 'Setiap kombinasi jadi satu visual dekorasi utuh, dalam hitungan detik.',
    // photo = index ke MOCK_PHOTOS (src/lib/mockPhotos.js)
    items: [
      { name: 'Gebyok Priangan', style: 'Jawa × Sunda', photo: 0 },
      { name: 'Bali Kontemporer', style: 'Bali × Modern', photo: 1 },
      { name: 'Rumah Gadang Alami', style: 'Minang × Rustic', photo: 2 },
      { name: 'Keraton Nusantara', style: 'Jawa × Nasional', photo: 3 },
      { name: 'Betawi Segar', style: 'Betawi × Tropis', photo: 4 },
      { name: 'Saung Modern', style: 'Sunda × Kontemporer', photo: 0 },
    ],
  },

  footer: {
    tagline: 'Ketik dekorasi impianmu, lihat langsung jadi gambar. Untuk hasil final yang rapi, tim kami siap membantu.',
    note: 'Versi awal — generate dan simpan desain sudah bisa dicoba. Pembayaran dan opsi tim akan segera menyusul.',
  },
}
