// Semua copy landing page — satu versi netral, tanpa segmentasi audience.
// Konsep: self-serve — user ketik keinginan → AI generate gambar dekorasi.
// Opsi lanjut: "dikerjain tim" untuk aset final rapi (hybrid monetisasi).

export const content = {
  brand: 'Decora AI',
  nav: [
    { label: 'Coba', href: '#generator' },
    { label: 'Cara Kerja', href: '#cara-kerja' },
    { label: 'Contoh Hasil', href: '#portofolio' },
    { label: 'Harga', href: '#harga' },
    { label: 'FAQ', href: '#faq' },
  ],

  hero: {
    eyebrow: 'Desain Dekorasi Wedding, Dibantu AI',
    headline: 'Ketik dekorasi impianmu, lihat langsung jadi gambar.',
    sub: 'Masukin gaya, budaya, warna, dan budget yang kamu mau — AI langsung generate visualnya dalam hitungan detik. Buat dibayangkan matang, dipakai presentasi, atau negosiasi vendor. Butuh hasil final rapi? Serahkan ke tim.',
    ctaPrimary: 'Buat Desain Wedding',
    ctaSecondary: 'Lihat Contoh Hasil',
    stat: [
      { value: 'Langsung jadi', label: 'Ketik → gambar dalam detik' },
      { value: 'Paham budaya lokal', label: 'Gebyok, paes ageng, janur, dst' },
      { value: 'Upgrade ke tim', label: 'Untuk aset final siap pakai' },
    ],
  },

  problems: {
    eyebrow: 'Kenapa ini bantu kamu',
    title: 'Susah membayangkan hasil sebelum keluar budget.',
    items: [
      {
        title: 'Trial-error yang mahal',
        body: 'Susah membayangkan hasil dekorasi sebelum booking vendor atau presentasi ke klien. Sekarang tinggal ketik, kamu lihat bayangannya dulu — tanpa coba-coba mahal.',
      },
      {
        title: 'Susah bilang "aku mau seperti ini"',
        body: 'Butuh sesuatu yang bisa dipakai buat negosiasi atau presentasi, tanpa harus sewa decorator penuh dulu. Generate gambarnya sendiri, tunjukin langsung.',
      },
      {
        title: 'Referensi online sering gak nyambung',
        body: 'Pinterest & tools generic sering gak sesuai budget, gaya lokal, atau kombinasi budaya yang kamu mau — termasuk Jawa × modern. Di sini kamu tentukan sendiri.',
      },
    ],
  },

  howItWorks: {
    eyebrow: 'Cara kerja',
    title: 'Dari ketikan, jadi gambar nyata.',
    sub: 'Coba sepuasnya sampai nemu yang sreg. Butuh hasil final rapi? Serahkan ke tim.',
  },

  packages: {
    eyebrow: 'Paket & harga',
    title: 'Coba gratis, upgrade kalau butuh lebih.',
    sub: 'Mulai gratis buat generate sendiri. Volume rutin atau butuh hasil final rapi? Ada paket buat itu.',
    note: 'Halaman pra-validasi — harga di bawah ilustrasi, mesin generate masih dalam pengembangan.',
    plans: [
      {
        name: 'Gratis',
        price: 'Rp0',
        tagline: 'Coba generate dekorasi impianmu',
        featured: false,
        features: [
          'Beberapa generate per hari',
          'Gaya & budaya dasar',
          'Resolusi standar (ada watermark)',
          'Simpan hasil favorit',
        ],
        cta: 'Coba Gratis',
      },
      {
        name: 'Plus',
        price: 'Langganan bulanan',
        tagline: 'Generate lebih bebas, hasil lebih bagus',
        featured: true,
        features: [
          'Generate tanpa batas wajar',
          'Resolusi HD tanpa watermark',
          'Semua gaya & kombinasi budaya',
          'Riwayat & simpan banyak konsep',
        ],
        cta: 'Mulai Plus',
      },
      {
        name: 'Aset Final (Tim)',
        price: 'Per project',
        tagline: 'Dikerjain tim, siap presentasi & produksi',
        featured: false,
        features: [
          'Finalisasi jadi vector rapi berlayer',
          'Dikurasi pakem budaya oleh manusia',
          'Mockup presentasi siap pakai',
          'Revisi terbatas termasuk',
        ],
        cta: 'Serahkan ke Tim',
      },
    ],
  },

  testimonials: {
    eyebrow: 'Kata mereka',
    title: 'Dipakai buat bayangin hasil sebelum keluar budget.',
    items: [
      {
        quote: 'Aku ketik bayangan dekorasiku, langsung muncul gambarnya. Nunjukin ke vendor jadi gampang banget — gak perlu ribet jelasin.',
        name: 'Dinda & Bagas',
        role: 'Menikah 2026, Jawa × modern',
      },
      {
        quote: 'Tinggal ketik gaya yang klien mau, beberapa detik udah ada opsi visual buat presentasi. Yang final tinggal gue serahkan ke tim.',
        name: 'Rangga P.',
        role: 'Owner, studio dekorasi (Yogyakarta)',
      },
      {
        quote: 'Enaknya paham istilah adat. Ketik "paes ageng" langsung nyambung — gak keluar hasil ngawur kayak tools generic.',
        name: 'Sekar A.',
        role: 'Freelance wedding decorator',
      },
    ],
  },

  faq: {
    eyebrow: 'FAQ',
    title: 'Pertanyaan yang sering ditanyakan.',
    items: [
      {
        q: 'Ini beneran langsung jadi gambar?',
        a: 'Ya. Ketik gaya, budaya, warna, dan elemen yang kamu mau — AI menghasilkan visual dekorasinya dalam hitungan detik. Bisa diutak-atik dan generate ulang sampai pas.',
      },
      {
        q: 'Apakah ini menggantikan jasa decorator?',
        a: 'Bukan. Ini bantu kamu membayangkan matang dan presentasi/negosiasi lebih jelas. Eksekusi fisik tetap oleh vendor/decorator. Butuh hasil rapi siap produksi? Upgrade ke opsi tim.',
      },
      {
        q: 'Seberapa akurat dengan pakem budaya?',
        a: 'AI kami dilatih paham gaya & istilah lokal, jauh lebih nyambung dari tools generic. Untuk yang benar-benar pakem & siap produksi, opsi tim — manusia berpengalaman adat — jadi quality gate.',
      },
      {
        q: 'Bisa dipakai komersial?',
        a: 'Bisa. Hasil generate maupun aset final boleh dipakai untuk presentasi, proposal, maupun negosiasi ke klien atau vendor.',
      },
      {
        q: 'Kalau hasil generate belum pas gimana?',
        a: 'Ubah keinginanmu dan generate lagi — sepuasnya di paket berbayar. Atau serahkan ke tim untuk penyempurnaan oleh manusia.',
      },
    ],
  },

  generator: {
    eyebrow: 'Coba sekarang',
    title: 'Tulis keinginanmu, lihat hasilnya.',
    sub: 'Makin detail — gaya, budaya, warna, elemen wajib — makin nyambung hasilnya.',
    placeholder: 'Contoh: pelaminan Jawa modern, dominan putih & emas, ada gebyok ukir & janur, nuansa hangat, budget menengah',
    chips: ['Jawa Klasik', 'Jawa × Modern', 'Rustic Garden', 'Sunda', 'Intimate', 'Nasional'],
    button: 'Generate',
    loading: 'AI lagi meracik konsepmu…',
    emptyHint: 'Tulis keinginanmu di sebelah kiri, hasilnya muncul di sini.',
    resultTitle: 'Hasil generate',
    resultHint: 'Suka hasilnya? Utak-atik lagi, atau sempurnakan dengan tim.',
    regenerate: 'Generate lagi',
    upgradeCta: 'Sempurnakan dengan tim',
    note: 'Hasil ini ilustratif — mesin generate AI masih dalam pengembangan. Daftar buat jadi yang pertama coba versi aslinya.',
  },

  reference: {
    label: 'Referensi gambar (opsional)',
    hint: 'Upload foto lokasi, Pinterest, atau referensi gaya yang kamu suka',
    add: 'Tambah gambar referensi',
    change: 'Ganti gambar',
    remove: 'Hapus',
  },

  // Copy untuk area aplikasi (setelah login). Satu bahasa dengan landing —
  // uiuxcontext.md: satu pengalaman produk yang konsisten, bahasa Indonesia.
  app: {
    auth: {
      title: 'Masuk ke Decora AI',
      registerTitle: 'Buat akun Decora AI',
      sub: 'Lanjutkan mendesain dekorasi pernikahanmu.',
      registerSub: 'Gratis — langsung mulai desain pertamamu.',
      emailLabel: 'Email',
      passwordLabel: 'Kata sandi',
      nameLabel: 'Nama',
      submit: 'Masuk',
      registerSubmit: 'Daftar',
      submitting: 'Sebentar…',
      google: 'Lanjutkan dengan Google',
      or: 'atau',
      toRegister: 'Belum punya akun? Daftar',
      toLogin: 'Sudah punya akun? Masuk',
      note: 'Versi demo — kredensial apa pun diterima.',
    },
    shell: {
      projects: 'Proyek',
      settings: 'Pengaturan',
      logout: 'Keluar',
      saving: 'Menyimpan…',
      saved: 'Tersimpan',
      notSynced: 'Belum tersinkron',
      notSyncedHint: 'Perubahan tersimpan di perangkat ini; sinkronisasi server dicoba ulang',
    },
    library: {
      title: 'Proyek',
      welcome: (name) => `Halo, ${name} 👋`,
      newProject: 'Proyek baru',
      statProjects: 'Proyek aktif',
      statDesigns: 'Total desain',
      statFavorites: 'Favorit',
      statToday: 'Desain hari ini',
      planFree: 'Gratis',
      planPlus: 'Plus',
      planUpgrade: 'Upgrade',
      continueTitle: 'Lanjutkan mengerjakan',
      continueCta: 'Buka Studio →',
      continueUpdated: 'Terakhir diperbarui',
      emptyTitle: 'Mulai desain pertamamu',
      emptyBody: 'Jawab beberapa pertanyaan tentang pernikahanmu — AI langsung membuatkan konsepnya.',
      designCount: 'desain',
      updated: 'Diperbarui',
      rename: 'Ubah nama',
      duplicate: 'Duplikat',
      delete: 'Hapus',
      deleteTitle: (name) => `Hapus '${name}'?`,
      deleteBody: (n) => `Proyek beserta ${n} desainnya akan dihapus. Tindakan ini tidak bisa dibatalkan.`,
      deleted: (name) => `"${name}" dihapus`,
      undo: 'Urungkan',
      cancel: 'Batal',
      degraded: 'Menampilkan desain yang tersimpan di perangkat ini. Sinkronisasi server tidak tersedia.',
    },
    wizard: {
      title: 'Ceritakan pernikahanmu',
      editTitle: 'Ubah setup',
      sub: 'Hanya tema dan venue yang wajib — sisanya bikin desainnya makin pas.',
      teaserNotice: 'Proyekmu sudah dimulai dari idemu — tambahkan beberapa detail biar hasilnya makin bagus.',
      nameLabel: 'Nama proyek',
      defaultName: 'Pernikahan tanpa judul',
      sectionWedding: 'Pernikahannya',
      sectionVenue: 'Venuenya',
      sectionLook: 'Tampilannya',
      themeLabel: 'Tema',
      themeError: 'Pilih tema dulu untuk lanjut',
      styleLabel: 'Gaya (opsional)',
      venueLabel: 'Tipe venue',
      venueError: 'Pilih tipe venue dulu untuk lanjut',
      venueSizeLabel: 'Ukuran venue',
      guestLabel: 'Jumlah tamu',
      guestUnit: 'tamu',
      guestClamped: (min, max) => `Dijaga antara ${min} dan ${max}.`,
      budgetLabel: 'Kelas budget',
      budgetHelper: 'Menentukan semewah apa tampilan desainnya.',
      paletteLabel: 'Palet warna (opsional)',
      paletteLimit: 'Maksimal 3 warna biar desainnya tetap serasi.',
      paletteCustom: 'Kustom',
      paletteAdd: 'Tambah',
      notesLabel: 'Catatan tambahan (opsional)',
      notesPlaceholder: 'Hal spesifik — mis. banyak lampu tumblr, floral arch, tanpa warna merah.',
      customPlaceholder: 'Tuliskan sendiri',
      cancel: 'Batal',
      preview: 'Pratinjau prompt →',
      backToForm: '← Ubah detail',
      promptEyebrow: 'Prompt generate-mu',
      promptNote: 'Silakan ubah kata-katanya. Jawabanmu di atas sudah terangkum di sini.',
      recompileBanner: 'Kamu mengubah prompt ini manual.',
      recompileAction: 'Susun ulang dari jawabanmu',
      recompileKeep: 'atau pertahankan versimu.',
      generate: 'Buat desain ✦',
      saveChanges: 'Simpan perubahan',
      creating: 'Menyimpan…',
      notFound: 'Proyek ini tidak ada atau sudah dihapus.',
      backToProjects: 'Kembali ke proyek',
    },
    studio: {
      emptyTitle: 'Belum ada desain',
      emptyBody: 'Tulis catatan di bawah (atau langsung tekan Buat Desain) untuk melihat konsep pertamamu.',
      design: 'Desain',
      generating: 'Membuat…',
      generatingElapsed: 'Membuat desain…',
      patience: 'Desain yang kompleks bisa butuh sampai beberapa menit.',
      generate: 'Buat Desain',
      composerPlaceholder: 'Tulis apa yang mau diubah — atau kosongkan untuk membuat ulang',
      analyze: 'Analisis',
      viewChecklist: 'Lihat checklist',
      export: 'Ekspor',
      useAsReference: 'Jadikan referensi',
      isReference: 'Referensi ✓',
      refChip: 'Ref: Desain',
      removeRef: 'Hapus referensi',
      retry: 'Coba lagi',
      prompt: 'Prompt',
      tabSetup: 'Setup',
      tabHistory: 'Riwayat',
      tabAnalyze: 'Analisis',
      analyzingBadge: 'Sedang dianalisis →',
      editSetup: 'Ubah setup',
      historyEmpty: 'Belum ada desain.',
      setupTheme: 'Tema',
      setupStyle: 'Gaya',
      setupVenue: 'Venue',
      setupSize: 'Ukuran',
      setupGuests: 'Tamu',
      setupBudget: 'Budget',
      setupPalette: 'Palet',
      setupUpdated: 'Setup baru berlaku untuk desain berikutnya',
      designReady: 'Desain berhasil dibuat ✓',
      designFailed: 'Desain gagal dibuat',
      projectSaved: 'Proyek tersimpan ✓',
      notFound: 'Proyek ini tidak ada atau sudah dihapus.',
      backToProjects: 'Kembali ke proyek',
      errCap: (n) => `Batas desain harian proyek ini tercapai (${n}). Coba lagi besok.`,
      errConnectivity: 'Layanan desain tidak bisa dihubungi. Promptmu aman — coba lagi.',
      lightboxDownload: 'Unduh PNG',
      lightboxAnalyze: 'Analisis',
      lightboxClose: 'Tutup',
      sidebarProjects: 'Proyek',
      sidebarFeed: 'Feed',
      confirmGenerateTitle: 'Buat desain ini?',
      confirmGenerateBody: 'Proses ini memakai kredit AI generate gambar dan bisa butuh waktu beberapa menit. Pastikan promptmu sudah sesuai.',
      confirmGenerateCta: 'Ya, buat desain',
      cancel: 'Batal',
      cancelGenerating: 'Batalkan',
      cancelled: 'Dibatalkan',
    },
    analyze: {
      title: 'Checklist dekorasi',
      design: 'Desain',
      // Peta label tampilan ID — nilai data/enum tetap EN (tersimpan di project & schema server).
      categoryLabels: {
        Stage: 'Panggung',
        Backdrop: 'Backdrop',
        Chairs: 'Kursi Tamu',
        'VIP Chairs': 'Kursi VIP',
        Tables: 'Meja',
        Flowers: 'Bunga',
        Lighting: 'Pencahayaan',
        Walkway: 'Jalur Masuk',
        'Reception Desk': 'Meja Penerima Tamu',
        'Ceiling Decoration': 'Dekorasi Plafon',
        'LED Screen': 'Layar LED',
        Other: 'Lainnya',
      },
      costLabel: 'Estimasi biaya (Rp)',
      costChipPrefix: 'Rp',
      costTotal: 'Estimasi total',
      findVendors: 'Butuh vendor untuk mewujudkannya? Lihat vendor →',
      noDesignTitle: 'Belum ada desain',
      noDesignBody: 'Buat desain dulu di feed sebelah kiri, baru bisa dianalisis di sini.',
      jumpToFeed: 'Lihat di feed',
      cta: 'Analisis desain ini ✦',
      ctaHint: 'Butuh sekitar 15 detik.',
      analyzing: 'Menganalisis… ±15 detik',
      complete: 'Analisis selesai ✓',
      error: 'Desain ini belum bisa dianalisis. Coba lagi, ya.',
      retry: 'Coba lagi',
      zeroTitle: 'Belum ada item terdeteksi',
      zeroBody: 'Item dekorasi di desain ini belum bisa dikenali. Kamu bisa menambahkannya manual.',
      addItem: '＋ Tambah item',
      reanalyze: 'Analisis ulang',
      reanalyzeConfirm: 'Checklist beserta editanmu akan diganti. Analisis ulang?',
      cancel: 'Batal',
      exportBrief: 'Ekspor brief →',
      note: 'Catatan',
      generateItemImage: 'Buat gambar item',
      generatingItemImage: 'Membuat gambar item…',
      itemImageReady: 'Gambar item selesai ✓',
      itemImageError: 'Gambar item ini belum bisa dibuat. Coba lagi, ya.',
      regenerateItem: 'Buat ulang / kustomisasi',
      itemPromptPlaceholder: 'Opsional: jelaskan perubahan, mis. emas bukan perak',
      itemGenerate: 'Buat',
      itemGenerating: 'Membuat…',
      itemCancelling: 'Batalkan',
      itemCancelled: 'Dibatalkan',
      confirmItemTitle: 'Buat gambar item ini?',
      confirmItemBody: 'Proses ini memakai kredit AI generate gambar.',
      confirmItemCta: 'Ya, buat gambar',
    },
    compare: {
      action: 'Bandingkan',
      selected: 'Dipilih ✓',
      bar: (n) => `${n}/2 desain dipilih untuk dibandingkan`,
      open: 'Bandingkan sekarang',
      clear: 'Batal',
      title: 'Bandingkan desain',
      close: 'Tutup',
    },
    favorite: {
      add: 'Tandai favorit',
      remove: 'Hapus dari favorit',
    },
    share: {
      option: 'Link berbagi',
      optionDesc: 'Salin link lihat-saja untuk dikirim ke pasangan atau vendor.',
      copy: 'Salin link',
      copied: 'Link berbagi disalin ✓',
      copyFailed: 'Gagal menyalin — salin manual dari address bar.',
      pageTitle: 'Dibagikan dari Decora AI',
      pageNote: 'Halaman lihat-saja. Buat desainmu sendiri di Decora AI.',
      pageCta: 'Coba Decora AI',
      notFound: 'Link berbagi ini tidak valid atau desainnya sudah dihapus.',
    },
    vendors: {
      title: 'Vendor Dekorasi',
      sub: 'Vendor pilihan yang siap mewujudkan konsep desainmu. (Demo — data contoh)',
      contact: 'Hubungi vendor',
      contacted: 'Permintaan terkirim ke vendor ✓ (demo)',
      specialty: 'Spesialisasi',
      backToStudio: '← Kembali',
      list: [
        { name: 'Arunika Decor', city: 'Jakarta', specialty: 'Rustic & Garden', rating: 4.9, projects: 120 },
        { name: 'Gebyok Nusantara', city: 'Yogyakarta', specialty: 'Adat Jawa Klasik', rating: 4.8, projects: 200 },
        { name: 'Serenity Wedding', city: 'Bandung', specialty: 'Modern Minimalis', rating: 4.7, projects: 85 },
        { name: 'Puspa Kencana', city: 'Surabaya', specialty: 'Glamorous Ballroom', rating: 4.8, projects: 150 },
        { name: 'Bale Agung Decor', city: 'Bali', specialty: 'Outdoor & Beach', rating: 4.9, projects: 95 },
        { name: 'Selaras Pelaminan', city: 'Semarang', specialty: 'Sunda & Nasional', rating: 4.6, projects: 110 },
      ],
    },
    billing: {
      title: 'Paket & Tagihan',
      current: 'Paket saat ini',
      free: 'Gratis',
      plus: 'Plus',
      freeDesc: 'Beberapa generate per hari, resolusi standar.',
      plusDesc: 'Generate tanpa batas wajar, resolusi HD tanpa watermark.',
      upgrade: 'Upgrade ke Plus',
      downgrade: 'Kembali ke Gratis',
      upgraded: 'Berhasil upgrade ke Plus ✓ (demo)',
      downgraded: 'Kembali ke paket Gratis (demo)',
      demoNote: 'Demo — belum ada pembayaran sungguhan.',
    },
    export: {
      title: (n) => `Ekspor Desain ${n}`,
      png: 'Gambar (PNG)',
      pngDesc: 'Gambar desain dalam resolusi penuh.',
      pdf: 'Brief vendor (PDF)',
      pdfDesc: 'Satu halaman: desain, detail pernikahan, dan checklist.',
      noChecklist: 'Belum ada checklist — brief hanya berisi desain + detail.',
      analyzeFirst: 'Analisis dulu',
      cancel: 'Batal',
      download: 'Unduh',
      preparing: 'Menyiapkan…',
      pngDone: 'Gambar terunduh ✓',
      pdfDone: 'Brief terunduh ✓',
      error: 'Gambar desain tidak bisa diambil. Cek koneksimu lalu coba lagi.',
    },
    settings: {
      title: 'Pengaturan',
      profile: 'Profil',
      nameLabel: 'Nama',
      emailLabel: 'Email',
      save: 'Simpan profil',
      saved: 'Tersimpan ✓',
      appInfo: 'Info aplikasi',
      dailyCap: 'Batas generate harian per proyek',
      language: 'Bahasa',
      languageValue: 'Indonesia',
      logout: 'Keluar',
    },
    notFound: {
      title: 'Halaman tidak ditemukan',
      cta: 'Kembali ke proyek',
    },
  },

  stepsList: [
    { icon: 'brief', title: 'Tulis keinginan', body: 'Ketik gaya, budaya, warna, elemen wajib, dan budget. Bisa pilih dari contoh gaya biar cepat.' },
    { icon: 'spark', title: 'AI generate gambar', body: 'Dalam hitungan detik, keluar beberapa opsi visual dekorasi yang paham gaya & istilah lokal.' },
    { icon: 'revise', title: 'Utak-atik langsung', body: 'Belum pas? Ubah keinginanmu dan generate ulang — sepuasnya sampai nemu yang sreg.' },
    { icon: 'deliver', title: 'Pakai buat vendor', body: 'Simpan gambar & mockup buat dibayangkan matang dan dipakai negosiasi dengan vendor.' },
    { icon: 'produce', title: 'Sempurnakan dengan tim', body: 'Opsional — upgrade biar dikerjain tim jadi aset rapi, dikurasi pakem budaya oleh manusia.', optional: true },
  ],

  gallery: {
    eyebrow: 'Contoh hasil',
    title: 'Dari ketikan singkat, jadi gambar.',
    sub: 'Beberapa contoh: tulis keinginanmu, keluar visual dekorasinya — tinggal pakai atau sempurnakan.',
    items: [
      { tag: 'Jawa Klasik', prompt: '"Gebyok + paes ageng, emas"', result: 'Pelaminan Jawa klasik' },
      { tag: 'Jawa × Modern', prompt: '"Panggung minimalis, putih"', result: 'Dekorasi modern' },
      { tag: 'Rustic Garden', prompt: '"Taman, kayu & bunga liar"', result: 'Dekorasi taman' },
      { tag: 'Sunda', prompt: '"Pelaminan Sunda, hangat"', result: 'Pelaminan Sunda' },
      { tag: 'Intimate', prompt: '"Intimate, lilin & putih"', result: 'Dekorasi intimate' },
      { tag: 'Nasional', prompt: '"Pelaminan megah, merah emas"', result: 'Pelaminan nasional' },
    ],
  },

  footer: {
    tagline: 'Ketik dekorasi impianmu, lihat langsung jadi gambar. Butuh hasil final rapi, tim siap bantu.',
    note: 'Status: pra-validasi. Halaman ini untuk mengukur minat. Generator & form belum aktif.',
  },
}
